# Generated by Django 4.1.7 on 2023-02-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
