# Generated by Django 4.1.7 on 2023-02-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_tags_options_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
