# Generated by Django 4.1.7 on 2023-02-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='one',
            field=models.BooleanField(default=False),
        ),
    ]
