# Generated by Django 4.1.7 on 2023-02-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_new_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='little_discription',
            field=models.TextField(default=False),
        ),
    ]
