# Generated by Django 4.1.7 on 2023-02-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_new_little_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emais', models.EmailField(max_length=254)),
            ],
        ),
    ]
