# Generated by Django 4.1.7 on 2023-02-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_emails_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='emais',
            new_name='emails',
        ),
    ]
