# Generated by Django 4.1.7 on 2023-02-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_emails_email_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='emais',
        ),
    ]
