# Generated by Django 4.1.7 on 2023-02-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_emais_email_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='emais',
        ),
    ]
