# Generated by Django 4.1.7 on 2023-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_email_email_emais'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
